### PR TITLE
mapping: Add @404boyfriend twitter archive

### PR DESCRIPTION
**Pull request by xdesro**
One question I had was: if I changed my username semi-recently, should I add that account name to mapping as well? Probably not I'd guess, cause most archives will have come from after the name change, but.

### CODE REVIEW

**Comment by nhoizey** [comment]
@xdesro I guess all the tweets in your archive have the new username, right?

But we already have @phoebethewitch with multiple usernames in history: https://github.com/tweetback/tweetback-canonical/pull/13

So I wonder:
- is it useful to add older usernames for our own archives?
- is it useful for links from others' archives?
- what if an old username has since been used by someone else?

**Comment by phoebethewitch** [comment]
reason i added my older usernames is i think i’ve seen twitter links quote retweets with the old username sometimes. they can be removed if needed though 🙂

**Comment by nhoizey** [comment]
Ok so @xdesro you can add your older username before we merge. 👍

**Comment by xdesro** [comment]
Done deal! Sorry about the delay.

**Comment by nhoizey** [comment]
@xdesro no problem! 👍

**Pull request merged**
